add a formatter that dedupes based on tid
seth-shaw-unlv/controlled_access_terms pull request #62
Opened 2021-02-26 23:46 UTC by elizoller

*There was a slack conversation around when an agent played multiple roles with regards to a single item, that the agent would appear multiple times in the typed relation field, once per role. this is a display add on that de-duplicates based on the taxonomy term id.

# What does this Pull Request do?
Dedupes repeated agents for display

# What's new?
* a field formatter

# How should this be tested?
* create a node that has at least 2 agents. they should link to the same taxonomy term but with different roles.
* view the node and the default typed relation formatter should repeat the agents name twice (or however many times you repeated the agent), once per role.
* apply this PR
* clear your cache
* view the node again - you should now see the agent name deduplicated
like ```Animator (anm), Depositor (dpt): Sump-Crethar, Nicole```

# Interested parties
 @Islandora/8-x-committers @seth-shaw-unlv

2021-02-26 23:53 UTC, seth-shaw-unlv commented
@dannylamb, Travis is broken again. [It says phpcpd isn't installed](https://travis-ci.com/github/Islandora/controlled_access_terms/jobs/486670677#L1410).

2021-02-26 23:54 UTC, elizoller commented
i'm sure i messed up some phpcpd stuff anyway in my haste to get this out on a friday afternoon haha

2021-02-26 23:56 UTC, seth-shaw-unlv commented
I don't think you copy/pasta'd anything that would trigger phpcpd... phpcs on the other hand.... 😉

2021-03-02 19:04 UTC, seth-shaw-unlv commented on src/Plugin/Field/FieldFormatter/TypedRelationDedupFormatter.php
> + *   id = "typed_relation_dedup_default",
I would remove "_default" from the id.

2021-03-02 19:16 UTC, seth-shaw-unlv requested changes
Just a nitpick that the ID shouldn't have "_default" since it isn't the default formatter for this field type. Otherwise, this looks good. 👍

2021-03-02 20:54 UTC, seth-shaw-unlv approved these changes
👍

2021-03-02 21:34 UTC, seth-shaw-unlv commented
Instead of forcing you to merge in the updates for Travis' sake, I'm just going merge it.

2021-03-02 21:34 UTC, merged