Add feeds target for edtf fields.
seth-shaw-unlv/controlled_access_terms pull request #74
Opened 2021-10-31 01:37 UTC by rosiel

**GitHub Issue**: https://github.com/islandora/documentation/issues/1976

# What does this Pull Request do?

Add a Feeds target for EDTF date fields

# What's new?

EDTF date target, which does validation.

# How should this be tested?

- composer require drupal/feeds
- set up a feed type to target a Repository Item content type.
- set up the feed with a mapping. Note you can set up mappings access many fields, but *not* the EDTF fields.
- install  this PR, clear cache, and you should be able to set up mappings to EDTF fields.
- import from the feeds with good and bad EDTF dates, and watch the bad dates get flagged (red errors show on screen) and the dates are not imported.

# Additional Notes:

I am baby dev. I'm not sure why but I couldn't access `$this->settings` unless i included the grandparent's `__construct` method. I am not sure if it's harmful but it's definitely not smooth.

# Interested parties
@seth-shaw-unlv @Islandora/8-x-committers

2021-11-01 16:28 UTC, seth-shaw-unlv commented
@rosiel, do you have an example feed or do I need to make a new one? I've never used feeds, so I don't know how involved it is.

2021-11-01 17:29 UTC, seth-shaw-unlv commented
To hasten testing I did a standard Drupal 8 install with feeds and controlled_access_terms installed. I added an EDTF field to Article and created a simple TSV for feeds:
```csv
id	title	body	pubdate
1	Cat GIFs	These are cat figgs	2021-11-01
2	A Few More Cat GIFs	Even more!	1980/2022
3	Even More Cat GIFs	Haz mor!	blah
```

Initial setup did not show my new EDTF date for the article content type as expected. Pulling in the PR then did show the Date field as an option. I ran the feed and was presented with:
<img width="1277" alt="Screen Shot 2021-11-01 at 10 07 43 AM" src="https://user-images.githubusercontent.com/29869988/139712227-cb88c11a-d66f-40dc-a077-dbcf73181be5.png">

The EDTF value `1980/2022` _should_ have worked, but it appears that the PR is still having issues accessing the settings values:
<img width="669" alt="Screen Shot 2021-11-01 at 10 21 09 AM" src="https://user-images.githubusercontent.com/29869988/139712999-c1180637-0cc8-43de-9c17-43a2050f144c.png">

Although, this makes sense, because I don't see anywhere for us to set these settings. The plugin should implement buildConfigurationForm (it currently inherits from [FieldTargetBase](https://git.drupalcode.org/project/feeds/-/blob/8.x-3.x/src/Plugin/Type/Target/FieldTargetBase.php#L337-358)), similar on [the existing EDTF field widget](https://github.com/Islandora/controlled_access_terms/blob/2.x/src/Plugin/Field/FieldWidget/EDTFWidget.php#L40-L72) 

Also, in regards to the setting variable, you can remove the variable definition and the constructor, as both of those inherit from parents. I removed them as an experiment and it didn't complain about settings being missing (just the same error of various undefined indexes in it).

2021-11-18 16:23 UTC, seth-shaw-unlv requested changes
Formalizing my earlier comments as a change request.

2021-11-18 16:23 UTC, seth-shaw-unlv commented on src/Feeds/Target/ExtendedDateTimeFormat.php
> +
We need to provide a `buildConfigurationForm` function to allow site administrators to update the various settings used in the `prepareValue` function ('intervals','sets', and 'strict_dates').

2021-11-18 16:23 UTC, seth-shaw-unlv commented on src/Feeds/Target/ExtendedDateTimeFormat.php
> +  protected $settings;
We already have a `$settings` from parent classes.

2021-11-18 16:23 UTC, seth-shaw-unlv commented on src/Feeds/Target/ExtendedDateTimeFormat.php
> +  public function __construct(array $configuration, $plugin_id, array $plugin_definition) {
Redundant to parent classes.

2021-11-18 17:11 UTC, rosiel commented
Thanks Seth!

2023-04-24 19:05 UTC, rosiel commented
Closing, no time to fix.

2023-04-24 19:05 UTC, closed without merging